#!/bin/bash

echo "🚗 Complete Parking System Setup"
echo "=================================="
echo ""
echo "This will:"
echo "1. Add more test data (including expired RFIDs)"
echo "2. Update payment calculation (ceiling/round up logic)"
echo ""
echo "Please enter your MySQL root password when prompted"
echo ""

# Add more test data
echo "📊 Adding test data..."
mysql -u root -p dbmsproject < add_more_test_data.sql

echo ""
echo "💰 Updating payment calculation..."
mysql -u root -p dbmsproject < update_payment_calculation.sql

echo ""
echo "✅ Setup Complete!"
echo ""
echo "=== TEST RFID UIDs ==="
echo ""
echo "✅ VALID RFIDs (will work):"
echo "  - RFID001 → KA01AB1234 (John Doe - Car)"
echo "  - RFID002 → KA02CD5678 (Jane Smith - SUV)"
echo "  - RFID003 → MH01EF9012 (Bob Wilson - Sedan)"
echo "  - RFID006 → TN05RS3333 (David Lee - Car)"
echo "  - RFID007 → MH06TU4444 (Emma Wilson - Sedan)"
echo ""
echo "❌ EXPIRED RFIDs (will be rejected by trigger):"
echo "  - RFID004 → KA03XY1111 (Alice - Motorcycle) [Expired 6 months ago]"
echo "  - RFID005 → DL04PQ2222 (Charlie - SUV) [Expired yesterday]"
echo ""
echo "=== PAYMENT CALCULATION ==="
echo ""
echo "New Rule: Always charge for FULL hours (ceiling/round up)"
echo ""
echo "Examples with Regular slot (₹50/hour):"
echo "  - Park for 10 minutes  → Charge 1 hour  = ₹50"
echo "  - Park for 30 minutes  → Charge 1 hour  = ₹50"
echo "  - Park for 60 minutes  → Charge 1 hour  = ₹50"
echo "  - Park for 61 minutes  → Charge 2 hours = ₹100"
echo "  - Park for 90 minutes  → Charge 2 hours = ₹100"
echo "  - Park for 121 minutes → Charge 3 hours = ₹150"
echo ""
echo "Examples with Premium slot (₹75/hour):"
echo "  - Park for 30 minutes  → Charge 1 hour  = ₹75"
echo "  - Park for 61 minutes  → Charge 2 hours = ₹150"
echo ""
echo "Examples with Motorcycle slot (₹30/hour):"
echo "  - Park for 30 minutes  → Charge 1 hour  = ₹30"
echo "  - Park for 61 minutes  → Charge 2 hours = ₹60"
echo ""
echo "=== NEXT STEPS ==="
echo ""
echo "1. Make sure .env has your MySQL password:"
echo "   DB_PASSWORD=your_password"
echo "   PORT=5001"
echo ""
echo "2. Start backend:"
echo "   PORT=5001 node server/index.js &"
echo ""
echo "3. Go to: http://localhost:3000/scanner"
echo ""
echo "4. Test scenarios:"
echo "   a) Enter RFID001 → Should work (valid)"
echo "   b) Enter RFID004 → Should fail (expired RFID)"
echo "   c) Park and exit quickly → Should charge 1 hour minimum"
echo ""
